blank_issues_enabled: true
contact_links:
  - name: Feature Request
    url: https://github.com/lionpanel-dev/panel/discussions
    about: Suggest a new feature or improvement for the software.
  - name: Installation Help
    url: https://lionpanel.dev/discord
    about: Please visit our Discord for help with your installation.
  - name: General Question
    url: https://lionpanel.dev/discord
    about: Please visit our Discord for general questions about LionPanel.
